### ISSUE TITLE
Viewing the Netherlands shows Caribbean Netherlands

### ISSUE THREAD

**Issue by lorrden** [siaw23/kovid#106]
I don't think this is the intention... same for the compare command.

```
➜  ~ kovid country netherlands
+-------+-------------+--------+--------------+-----------+
|                🇧🇶​ CARIBBEAN NETHERLANDS                 |
+-------+-------------+--------+--------------+-----------+
| Cases | Cases Today | Deaths | Deaths Today | Recovered |
+-------+-------------+--------+--------------+-----------+
| 2     | 0           | 0      | 0            | 0         |
+-------+-------------+--------+--------------+-----------+
```

**Comment by siaw23** [comment]
Thanks for reporting this. To be sure you're getting a specific country's data, you can always use the ISO2 codes in place of the country name. 

I have pushed a quick fix for this so if you upgrade your gem it should work now. With that said, I feel there's going to be more work on this with other country names which will take some bit of effort.

I'll close this now, please feel free to re-open if there'll be more issues regarding this.
