### ISSUE TITLE
Add a new command `kovid top N`

### ISSUE THREAD

**Issue by siaw23** [siaw23/kovid#111]
Add a new command that returns `top N` by deaths and cases.

**Comment by volfgox** [comment]
I want to work on this feature. Can I?

**Comment by siaw23** [comment]
Go for it @volfgox! 🙂

**Comment by volfgox** [comment]
@siaw23 Does it enough to list just top countries? Or top states or continents should be available?

**Comment by siaw23** [comment]
It'd be nice if you can add that too but you don't have to :)

**Comment by siaw23** [comment]
But don't bother with continents at all I don't think that'll be useful @volfgox 😃

**Comment by volfgox** [comment]
@siaw23 Do you agree with the following command?
```
Usage:
  kovid top

Options:
  -c, [--count=N]                
                                 # Default: 5
      [--in=IN]                  
                                 # Default: cases
                                 # Possible values: cases, deaths
      [--states], [--no-states]  

Returns top countries or states in an incident (number of cases or deaths).
```

**Comment by siaw23** [comment]
I don't think the `--in` flag provides a clear communication.

How about `kovid top 4 -d` for "top 4 in deaths" and `kovid top 7 -c` for "top 7 in cases"?

What do you think?

**Comment by volfgox** [comment]
Agree. And you think `--states` flag is good enough?

**Comment by siaw23** [comment]
For states, it can be `kovid states top N`.

**Comment by volfgox** [comment]
To preserve consistency in the CLI, I think `top` should be the main command everywhere in this context and `states` could be just a switch or a sub-command. For instance:
```
kovid top N --states
```
or:
```
kovid top states N 
```

**Comment by siaw23** [comment]
Perfect idea! `kovid top N --states` sound good actually. Then we can also do `kovid top N --countries` OR the shorter form `kovid top N -s | -c`

But then how would user pick by deaths? 

Do you think this would be better `kovid top N --states --deaths | --cases`?

**Comment by volfgox** [comment]
There will be 4 different switches for `top` command:

- `--countries`: has priority over `--states` and is the default switch
- `--states`
- `--cases`: has priority over `--deaths` and is the default switch. The alias is: `-c`
- `--deaths`: the alias is `-d`

So, `kovid top N` will be equivalent to `kovid top N --countries --cases`.

**Comment by siaw23** [comment]
Sounds good to me!
