### ISSUE TITLE
CLI Table shows Active Cases on the "Recovered" column

### ISSUE THREAD

**Issue by jsantos** [siaw23/kovid#116]
Noticed this today when I saw the Singapore column with 12.950 recovered case. I recalled from the news earlier today that this is not the number of recovered patients, but the number of Active Cases. 

As I see on [`/lib/kovid/tablelize.rb`](https://github.com/siaw23/kovid/blob/master/lib/kovid/tablelize.rb#L140), the `country_row` method only mentions `active` cases and not `recovered`.

I've obtained this result with `kovid check singapore` and by comparing to other countries.

**Comment by siaw23** [comment]
Hi, thanks a lot for reporting this.

I've fixed this and pushed a new version of the gem, you can confirm the fix by upgrading your gem with `gem update kovid` followed by your command `kovid check singapore`.

**Comment by jsantos** [comment]
I guess it's still not working. There's a mismatch between rows and a column with a empty header. I'll tinker with this a bit and will submit a PR :)

**Comment by siaw23** [comment]
Interesting. This is a screenshot from my machine with a response from the API. Looks like the "Active" and "Recovered" columns match. Isn't the data in my screenshot the same as what you have?
<img width="818" alt="Screenshot 2020-06-06 at 04 49 37" src="https://user-images.githubusercontent.com/4806407/83934421-406a9c00-a7b1-11ea-9329-58abf1162f0a.png">

**Comment by jsantos** [comment]
@siaw23 Oops sorry, I was already looking into the code, but after seeing your screenshot I uninstalled the gem and installed it again (previously had just updated) and the results show up correctly. 

Anything that might have been cached between versions?

**Comment by siaw23** [comment]
Oh right. "Recovered" and "Tests" should shift to the right and make space for "Active". Want to give this a shot? @jsantos 

> Oops sorry, I was already looking into the code, but after seeing your screenshot I uninstalled the gem and installed it again (previously had just updated) and the results show up correctly.

That shouldn't happen either, caching is 15min, unless you check within this time range.

**Comment by jsantos** [comment]
> Oh right. "Recovered" and "Tests" should shift to the right and make space for "Active". Want to give this a shot? @jsantos

Sure! On it.
