### ISSUE TITLE
kovid top N --death not working

### ISSUE THREAD

**Issue by siaw23** [siaw23/kovid#119]
`kovid top 10 --death` is not working but `kovid top 10 -d` works OK. 

Let's fix `kovid top 10 --death`

Output:

ERROR: "kovid top" was called with arguments ["10", "--death"]
Usage: "kovid top N"

**Comment by volfgox** [comment]
Because the switch is `--deaths`. Not `--death`.

**Comment by siaw23** [comment]
Aha! The owner of this feature speaks up.
