### ISSUE TITLE
broken with ActiveSupport error

### ISSUE THREAD

**Issue by apotheon** [siaw23/kovid#121]
.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-7.0.2.2/lib/active_support/xml_mini.rb:184:in `current_thread_backend': uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState (NameError)

**Comment by siaw23** [comment]
Thank you for this issue. Looks like we depend on a gem that's broken because of updates in AS. There's an umerged PR https://github.com/carmen-ruby/carmen/pull/298 for this. I'm thinking of looking of alternatives or forking that gem. A PR will be very welcome. 😊

**Comment by apotheon** [comment]
I commented on the pull request for carmen.  Hopefully it spurs some action.  That simple `require` change does indeed make Kovid work locally.

I haven't looked at how carmen is used in Kovid yet, though.

**Comment by siaw23** [comment]
@Jberczel maybe you can help with this? Is there a chance you could help us find an alternative to Carmen or maybe fork and publish the fix mentioned in https://github.com/carmen-ruby/carmen/pull/298?

**Comment by Jberczel** [comment]
@siaw23 - It looks like carmen is only used to lookup state codes for USA.  I think we can just remove it and use a ruby hash to look those up?  I think when I originally added the carmen dependency, I expected us to be able to use it for other country and province lookups.

Let me know if you're okay with that approach, and I can submit a PR.

**Comment by siaw23** [comment]
I'm OK with that approach. I think we only look up states for USA so we might not need Carmen after all. Please submit a PR if you can. @Jberczel

**Comment by siaw23** [comment]
We have a [fix](https://github.com/siaw23/kovid/pull/122) for this thanks to @Jberczel. @apotheon you can upgrade to see if this works as should. 😀

**Comment by apotheon** [comment]
The code looks functional and the fix works well so far.  Thanks!
