### ISSUE TITLE
Add CLI command for country and state lists

### ISSUE THREAD

**Issue by joshRpowell** [siaw23/kovid#24]
Great idea! Thanks for the wonderful tool.

Would be helpful to add CLI for list of country and states

```
kovid check puerto rico
kovid state puerto rico
```

both return `ERROR`

**Comment by siaw23** [comment]
Please try `kovid check "puerto rico"`

Is Puerto Rico a state though? Not sure how best it should be treated.

**Comment by siaw23** [comment]
Closing this now then ;)
