### ISSUE TITLE
Add coronovirus facts

### ISSUE THREAD

**Issue by siaw23** [siaw23/kovid#3]

**Comment by anubhav8421** [comment]
Hey @siaw23 I would love to contribute on this. Please let me know the details of this issue if possible

**Comment by siaw23** [comment]
Hi! Thanks for jumping aboard!

The idea is to create a YAML of coronavirus stats. These facts can be found on government health websites like in the links below. Once there's a YAML file in place a new command can be created in `/lib/cli.rb` to pick at random some fact and display it. So then the command would be `kovid fact` to display a random fact from the YAML file.

https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/share-facts.html
https://www.who.int/health-topics/coronavirus#tab=tab_1

**Comment by siaw23** [comment]
I'll be closing this. Please feel free to reopen if you'll like to work on this. @anubhav8421
