### ISSUE TITLE
Support aggregated data for EU

### ISSUE THREAD

**Issue by lorrden** [siaw23/kovid#40]
Looking at data for the entire EU is very difficult. Can we get aggregated data for the EU somehow?

The US has state-level info, but there does not seem to be the opposite for the EU.

**Comment by siaw23** [comment]
Hi @lorrden, I'm not sure I understand this. EU has countries, so you can search on a per-country basis. Do you perhaps mean being able to search for regions within a specific EU country?

**Comment by lorrden** [comment]
Smaller regions would indeed be useful if it is published, but I was referring to larger groupings such as the whole of the EU (the Union is a special entity after all). In addition, I would add that it would also be useful to query for aggregated data at the continent level (which is of course a different aggregation from the EU).

**Comment by siaw23** [comment]
Great idea. This is doable absolutely. I have created #46 seeking help with the collection of codes, once any of those is done, we can go ahead with implementing this!

**Comment by siaw23** [comment]
Please update your gem with `gem update kovid` and run `kovid eu` let's see if that works for you.

**Comment by lorrden** [comment]
Works great in a terrifying way...

**Comment by siaw23** [comment]
First time seeing the numbers this way. It's sad and scary :(... we'll get through this!
