### ISSUE TITLE
`kovid history croatia 1` and `kovid country croatia` don't show the same data

### ISSUE THREAD

**Issue by vfonic** [siaw23/kovid#42]
I believe these two commands should show the same data. Perhaps `kovid history` should fetch current data as well?

**Comment by siaw23** [comment]
`kovid history` will only show information up until yesterday excluding today's data. While `kovid history croatia 1` will show info in the last FULL day.

`kovid country croatia` shows information up until now.

Does this clear things up for you? 

<img width="459" alt="Screenshot 2020-03-24 at 23 47 56" src="https://user-images.githubusercontent.com/4806407/77484257-5dd2cf80-6e2a-11ea-90fd-a15313463cb5.png">

**Comment by vfonic** [comment]
Yes, it does, thanks!

Seems like last two days are always the same numbers, but the data returns different numbers: https://corona.lmao.ninja/v2/historical

Perhaps that's a bug?

**Comment by siaw23** [comment]
Nice catch! I'm actually using the API v1 /historical. I may fix this in the coming days unless you'd fancy sending in a PR?

**Comment by vfonic** [comment]
I'm just looking into it. Seems like that's the data that v1 returns. v2 data seems more up to date, but it uses numbers in JSON instead of strings and this causes Tableize (I think) to raise error.

API website just became unavailable so I can't do much now. I'll see if I can find some time tomorrow.

**Comment by siaw23** [comment]
Sure! :)

**Comment by siaw23** [comment]
Fixed in https://github.com/siaw23/kovid/commit/297547584b41fe3ea01a0780b7560c57fd6744e1
