### ISSUE TITLE
Canadian provinces

### ISSUE THREAD

**Issue by joshleblanc** [siaw23/kovid#83]
I know the endpoint you're using returns province information with V2, not sure how much work it would be to integrate that into kovid. 

https://docs.corona.lmao-xd.wtf/version-2

**Comment by siaw23** [comment]
This would be a more detailed use case. But certainly, I don't intend building this into kovid, for existing countries! It'll be too much work. If however, you need it for Canada only I think it is easy for just one country(haven't checked how the JSON looks like yet) and you can build and send a PR, that said I actually don't see the API provides province data on Canada, unless I have the wrong link.

**Comment by joshleblanc** [comment]
It's the hopkins endpoint: https://corona.lmao.ninja/v2/jhucsse

Historical data for provinces are available with something like https://corona.lmao.ninja/v2/historical/canada/new%20brunswick

**Comment by joshleblanc** [comment]
It's the hopkins endpoint: https://corona.lmao.ninja/v2/jhucsse

Historical data for provinces are available with something like https://corona.lmao.ninja/v2/historical/canada/new%20brunswick
