### ISSUE TITLE
Problems setting up locally for testing

### ISSUE THREAD

**Issue by DylanAndrews** [siaw23/kovid#94]
Hi. Thanks for the gem! Very cool.

So I'm very new to local gem development and am having trouble getting my local clone to be in a state where I can test the command line functionality, and I need to get this working before I can contribute.

I've done the following and am not having any luck. Any help would be most appreciated. 

```
❯ bin/setup

bundle install
+ bundle install
Warning: the running version of Bundler (2.0.2) is older than the version that created the lockfile (2.1.4). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Using rake 12.3.3
Using ascii_charts 0.9.1
Using bundler 2.0.2
Using diff-lcs 1.3
Using docile 1.3.2
Using ffi 1.12.2
Using ethon 0.12.0
Using rainbow 3.0.0
Using unicode-display_width 1.7.0
Using terminal-table 1.8.0
Using thor 1.0.1
Using typhoeus 1.3.1
Using kovid 0.6.0 from source at `.`
Using rspec-support 3.9.2
Using rspec-core 3.9.1
Using rspec-expectations 3.9.1
Using rspec-mocks 3.9.1
Using rspec 3.9.0
Using simplecov-html 0.12.2
Using simplecov 0.18.5
Bundle complete! 4 Gemfile dependencies, 20 gems now installed.
Bundled gems are installed into `./vendor`
```
Then 
```
❯ bundle exec rake install
kovid 0.6.0 built to pkg/kovid-0.6.0.gem.
kovid (0.6.0) installed.
```
Then
```
❯ kovid state Florida
Traceback (most recent call last):
	2: from /Users/dylanandrews/.asdf/installs/ruby/2.6.3/bin/kovid:23:in `<main>'
	1: from /Users/dylanandrews/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
/Users/dylanandrews/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem kovid (>= 0.a) with executable kovid (Gem::GemNotFoundException)
```

Any thoughts on what I'm doing wrong?

Thanks.

**Comment by siaw23** [comment]
Hi, thanks a lot for wanting to contribute! 

First of all, we'll need to clear the errors. Have you already tried `gem install bundler` like the error message is suggesting? Please first to upgrade your bundler version then we can go on from there. 

Also what ruby version are you on?

**Comment by DylanAndrews** [comment]
Thanks for the quick response. Ruby version `2.6.0`

```
❯ gem install bundler
Fetching bundler-2.1.4.gem
Successfully installed bundler-2.1.4
1 gem installed
```
then
```
❯ kovid state Florida
Traceback (most recent call last):
	2: from /Users/dylanandrews/.asdf/installs/ruby/2.6.3/bin/kovid:23:in `<main>'
	1: from /Users/dylanandrews/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
/Users/dylanandrews/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem kovid (>= 0.a) with executable kovid (Gem::GemNotFoundException)
```

**Comment by siaw23** [comment]
From this state just do `gem install kovid`. Once it's installed you can get into the console with the gem preloaded, with `bin/console`.

Please try `gem install kovid` first to see if we can get the gem installed.

**Comment by DylanAndrews** [comment]
For sure. So `gem install kovid` works just fine, and I can run `kovid state Florida` without issue. However, for local development, I want to ensure that when I run `kovid state Florida`, for example, it uses my local version of the gem so that I can see my changes reflected and ensure the feature I am adding is working. Not sure if I made that clear so I just wanted to clarify. To accomplish this(ensure my local version of the gem is being used)  I uninstalled my global version and ran the commands in my initial comment. Am I off base in my approach? Thanks again for the help.

**Comment by siaw23** [comment]
OK. Got lost a bit.

In this case, you can uninstall all versions of `kovid` with `gem uninstall kovid` and follow the prompts.

Then while you're inside the directory of your local `kovid` what do you get for `bundle version`? You may have to uninstall and reinstall your bundler if nothing works.

**Comment by DylanAndrews** [comment]
`Bundler version 2.1.4 (2020-01-05 commit 32a4159325)`

Also, just so you have as much info as possible, here are a few other things to note.

1. When I run `bin/setup` my gems are installed into a `vendor` directory.
2. The output I now get from running `kovid state Florida`, which I am now running after 1) uninstalling the gem 2) running `bin/setup` 3) running `bundle exec rake install, is now `No such command in 2.6.3 of ruby`. This is different from the error first mentioned, so I wanted to let you know.

**Comment by siaw23** [comment]
Interesting. While in the `kovid` folder please try `rake build && gem install pkg/kovid-0.6.0.gem`. Let's see what comes out of that. What are you using to manage your Ruby versions btw?

**Comment by DylanAndrews** [comment]
```
❯ rake build && gem install pkg/kovid-0.6.0.gem
rake aborted!
LoadError: cannot load such file -- rspec/core/rake_task
/Users/dylanandrews/Documents/personal_dev/kovid/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```

I use `asdf`

**Comment by siaw23** [comment]
Ok I've never used `asdf` before. It might have something to do with this.

With that said please do `bundle install` or `bin/setup` in your while in your `kovid` directory then try the  `rake build && gem install pkg/kovid-0.6.0.gem` command again.

**Comment by DylanAndrews** [comment]
I got it working. The issue was I wasn't running `bundle exec` before `rake build && gem install pkg/kovid-0.6.0.gem`. Thanks so much for the help!!
